services:
  postgres:
    image: postgres:16
    container_name: fastapi-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fastapi-redis
    restart: always
    ports:
      - "6380:6379"
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fastapi-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  meilisearch:
    image: getmeili/meilisearch
    container_name: fastapi-meilisearch
    restart: always
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: masterKey
    volumes:
      - meili_data:/meili_data

  app:
    build: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - meilisearch
    env_file:
      - .env

    volumes:
      - .:/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  
  consumer-worker:
    build: .
    container_name: fastapi-consumer-worker
    restart: always
    depends_on:
      - postgres
      - redis
      - rabbitmq
    env_file:
      - .env
    volumes:
      - .:/app
    command: python -m app.workers.start_consumers

  outbox-worker:
    build: .
    container_name: fastapi-outbox-worker
    restart: always
    depends_on:
      - postgres
      - redis
      - rabbitmq
    env_file:
      - .env
    volumes:
      - .:/app
    command: python -m app.workers.outbox_worker

  scheduler-worker:
    build: .
    container_name: fastapi-scheduler-worker
    restart: always

    depends_on:
      - postgres

    env_file:
      - .env

    volumes:
      - .:/app

    command: python -m app.workers.scheduler_worker

volumes:
  pgdata:
  meili_data: