"""multiple category

Revision ID: 0b96162faf49
Revises: a4e4edfa0982
Create Date: 2026-04-29 06:23:21.568893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b96162faf49'
down_revision: Union[str, Sequence[str], None] = 'a4e4edfa0982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_categorys',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('Category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'Category')
    )
    op.drop_column('books', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category', postgresql.ENUM('SCIENCE', 'ART', 'HISTORY', 'TECHNOLOGY', 'PROGRAMMING', 'BUSINESS', 'LITERATURE', name='category'), autoincrement=False, nullable=False))
    op.drop_table('book_categorys')
    # ### end Alembic commands ###
