"""borrow overdu become bool

Revision ID: 456911812dcb
Revises: d4e98316c105
Create Date: 2026-04-23 10:45:27.035943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456911812dcb'
down_revision: Union[str, Sequence[str], None] = 'd4e98316c105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrows', sa.Column('is_overdue', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrows', 'is_overdue')
    # ### end Alembic commands ###
