"""multiple category2

Revision ID: 65fac7df176c
Revises: 0b96162faf49
Create Date: 2026-04-29 07:07:42.731748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fac7df176c'
down_revision: Union[str, Sequence[str], None] = '0b96162faf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_categorys', sa.Column('category', sa.String(), nullable=False))
    op.drop_column('book_categorys', 'Category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_categorys', sa.Column('Category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('book_categorys', 'category')
    # ### end Alembic commands ###
