"""detail for book

Revision ID: 79ae0909c288
Revises: d36617da7cb6
Create Date: 2026-05-09 13:22:26.046038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ae0909c288'
down_revision: Union[str, Sequence[str], None] = 'd36617da7cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('external_provider', sa.String(), nullable=True))
    op.add_column('books', sa.Column('external_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'books', ['external_provider', 'external_id'])
    op.add_column('editions', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('editions', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('editions', 'description')
    op.drop_column('editions', 'isbn')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'external_id')
    op.drop_column('books', 'external_provider')
    # ### end Alembic commands ###
