"""lang to m to m

Revision ID: d36617da7cb6
Revises: e6129457e9d1
Create Date: 2026-05-06 07:48:32.268149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd36617da7cb6'
down_revision: Union[str, Sequence[str], None] = 'e6129457e9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editionlanguage',
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.PrimaryKeyConstraint('edition_id', 'language')
    )
    op.drop_column('editions', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('language', postgresql.ENUM('FA', 'EN', 'ARB', name='language_enm'), autoincrement=False, nullable=False))
    op.drop_table('editionlanguage')
    # ### end Alembic commands ###
