"""exp for user plan

Revision ID: e6129457e9d1
Revises: 65fac7df176c
Create Date: 2026-04-30 08:52:55.939301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6129457e9d1'
down_revision: Union[str, Sequence[str], None] = '65fac7df176c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan_expire', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan_expire')
    # ### end Alembic commands ###
